import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import localFont from "next/font/local";
import Sidebar from "@/components/layout/Sidebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const geistSans = localFont({
  src: "./fonts/GeistVF.woff", // Substitua com o caminho real para sua fonte
  variable: "--font-geistSans",  // Variável CSS para a fonte
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={`${geistSans.variable}  `}
    suppressHydrationWarning={true}
  >
        <body className="font-sans">
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex">
      <Sidebar />
      <main className="w-full flex-1 overflow-hidden">
        {/* <Header /> */}
        {children}
      </main>
    </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
